### ISSUE TITLE
4.3 makes DSC physical keypad unavailable 

### ISSUE THREAD

**Issue by yada75** [Cinntax/pyenvisalink#20]
Multiple HA users experienced DSC physical keypad unavailable and its directly related to added zone bypass future, more here:
[https://github.com/home-assistant/core/issues/65729](https://github.com/home-assistant/core/issues/65729)
[https://github.com/home-assistant/core/issues/65762](https://github.com/home-assistant/core/issues/65762)
[https://github.com/home-assistant/core/issues/65856](https://github.com/home-assistant/core/issues/65856)

**Comment by franciszek-koltuniuk-red** [comment]
https://github.com/Cinntax/pyenvisalink/blob/4e0f42678213b4e82dddcc2075bde62a67485270/pyenvisalink/dsc_client.py#L261

Keypress: _[*][1][#]_ is valid only for DSC systems if the user code is **not** required for bypass option.
If a user code is required, then a function _dump_zone_bypass_status()_ is in infinite loop - the request zone bypass status will always fail.

**Comment by yada75** [comment]
Excellent clarification @franciszek-koltuniuk-red.
So zone bypass should not be enabled by default, @Cinntax @ufodone can this be optional?

**Comment by ufodone** [comment]
Yikes!  Sorry about that.  I can certainly make it option as well as look into supporting it when a user code is required.

**Comment by dasb00ter** [comment]
Is this change big enough that it will make the update notes? I didn't see anything in the core notes for the update today February 9th. Forgive me my ignorance about how the pull request update system works.

**Comment by ufodone** [comment]
Are you referring to HA?  If so, then once these changes are approved, @Cinntax will have to push a new version the package and then I'll get a PR open with HA to pick up the new version.  I'm new to HA contributing but I assume once that PR is accepted it will show up in the release notes.

**Comment by Cinntax** [comment]
Hey everyone,  I have gone ahead and accepted the changes that @ufodone has made to resolve this issue, and released pyenvisalink v4.4- so that can be incorporated into HA.  I'll hold off on closing this until we've confirmed it's working.

On that note- I did want to mention that my housing situation changed a while back, and so I no longer have an envisalink, and can no longer test changes.  I'm willing to keep moving things along, but I'm unfortunately doing little other than slowing things down for all of you.  So I did want to see if any of you might be willing to take ownership of this package- I'd be happy to do what needs to be done to transfer ownership in github and in pypi. Thanks!

**Comment by yada75** [comment]
I can confirm that 4.4 fixes **DSC physical keypad unavailable** issue and is included in [HA 2022.2.6](https://www.home-assistant.io/blog/2022/02/02/release-20222/#release-202226---february-11)

Unfortunately zone bypass future had to be disabled in HA for now as changes in configuration.yaml was not allowed anymore
[https://github.com/home-assistant/core/pull/66243#pullrequestreview-878420355](https://github.com/home-assistant/core/pull/66243#discussion_r803369819)

**Comment by ufodone** [comment]
@yada75 I'll work on getting the zone bypass feature back into HA after I get my head wrapped around what needs to happen to sort out the config flow.  I'll also do a bit more research into whether there's a way to enable it for cases when the code is required for to bypass zones.  My initial investigation didn't reveal anything unfortunately.

@Cinntax I could potentially take over the package at some point.  Or alternatively (at least in the short term) would it make sense to add me as a collaborator so I could push changes myself?  I don't have a ton of free time these days and so other than getting the zone bypass feature re-enabled, I don't have any further plans.
