### ISSUE TITLE
SyntaxWarning: invalid escape sequence

### ISSUE THREAD

**Issue by allistermaguire** [Cinntax/pyenvisalink#32]
With the inclusion of python 3.12 https://github.com/python/cpython/issues/98401 in Home Assistant 2024.5.x, the following warnings are now appearing. https://github.com/home-assistant/core/issues/116123

```
Logger: py.warnings
Source: components/envisalink/init.py:6
First occurred: 21:16:14 (2 occurrences)
Last logged: 21:16:14

/usr/local/lib/python3.12/site-packages/pyenvisalink/honeywell_client.py:70: SyntaxWarning: invalid escape sequence '^' parse = re.match('([%^].+)$', rawInput)
/usr/local/lib/python3.12/site-packages/pyenvisalink/dsc_client.py:101: SyntaxWarning: invalid escape sequence '\d' if re.match('\d\d:\d\d:\d\d\s', rawInput):
```

It looks like they are fixed in v5.0.0b1, but that has progressed for a while. Do you think we can get a v4.7 released in the interim?

**Comment by ufodone** [comment]
Yes, I'll try and get a 4.7 release out soon.  I don't use the stock `envisalink` version in HA and so didn't seen the warnings.

**Comment by allistermaguire** [comment]
> Yes, I'll try and get a 4.7 release out soon. I don't use the stock `envisalink` version in HA and so didn't seen the warnings.

All good. Thank you @ufodone

**Comment by ufodone** [comment]
I've created a new 4.7 release and published it to PyPi.  It's been a while since I've done this so let me know if there's any problem.

**Comment by allistermaguire** [comment]
Hi @ufodone, yes 4.7 has been published. I have created HA PR here https://github.com/home-assistant/core/pull/118086
