### ISSUE TITLE
EnvisalinkAlarmPanel class overrides logging config

### ISSUE THREAD

**Issue by dhaustin** [Cinntax/pyenvisalink#34]
Thanks for all the  hard work.  Using this in a Samsung Smartthings environment and love it.

The EnvisalinkAlarmPanel class in alarm_panel.py currently overrides the logging configuration in the logging hierarchy when it is initialized.  This results in log messages being sent to syslog rather than the log file defined in the users root logger.  It also sets the logging level to DEBUG, which results in a lot of unnecessary logging if you are not in fact debugging.  If this is somehow necessary, allow the user to reset the logging config on the instance.

**Comment by ufodone** [comment]
I inherited this code and so am not sure why it was setup like that but I can't think why this would be necessary so I should be able to change it.

Are you using the 4.x or 5.x version?

**Comment by dhaustin** [comment]
Using 4.6.  Was unaware there is a 5.x version so will check into that.

**Comment by ufodone** [comment]
Sorry for the delay.  I've posted a new 4.8 release the the `logging.basicConfig` call removed.

I'll propagate that to the 5.x line in the future but have some other changes I need to sort out there first.
